### ISSUE TITLE
关于Segmentation fault解决

### ISSUE THREAD

**Issue by Flooooooooooooower** [yhlink/kssdtree#2]
您好，听了您在CGM的报告后，觉得这是一个很不错的软件，但是我在20个性染色体和一个外群作为ref在构建进化树过程中出现了问题。以下是我使用的方法和log，希望您能帮我解决！

```
kssdtree.quick(shuf_file='L3K10.shuf', genome_files='Genome', output='Z.newick', reference='X.fa.gz', method='nj', mode='r')
Step1...
Sketching...
rand_id=1800531731      half_ctx_len=10 hashsize=33554393       hashlimit=20132635
decomposing X.fa.gz
Sketch spend time：0.92s
Sketch finished!
Sketching...
rand_id=1800531731      half_ctx_len=10 hashsize=33554393       hashlimit=20132635
decomposing 1.fa
decomposing 2.fa
decomposing 3.fa
decomposing 4.fa
decomposing 5.fa
decomposing 7.fa
decomposing 8.fa
decomposing 9.fa
decomposing 10.fa
decomposing 11.fa
decomposing 12.fa
decomposing 13.fa
decomposing 14.fa
decomposing 15.fa
decomposing 16.fa
decomposing 17.fa
decomposing 18.fa
decomposing 19.fa
decomposing 20.fa
Sketch spend time：51.21s
Sketch finished!
Step2...
Subtracting...
Subtract spend time：0.04s
Subtract finished!
Step3...
Disting...
Warning: write mco file to an exists outdir:sruhqi367_subtract_sketch_1732935152
disf_sz=1444    refnum=19       qrynum=19       num_mapping_distf=0     batch_qrynum=19 1444    0
Segmentation fault (core dumped)
```

**Comment by Flooooooooooooower** [comment]
您好，我尝试解决了一下，已经可以成功得到了newick文件，但是最后一个问题，我也没有找到生成的visualization图片

```
Step3...
Disting...
Warning: write mco file to an exists outdir:cwqfmc378_subtract_sketch_1732937142
disf_sz=1444    refnum=19       qrynum=19       num_mapping_distf=0     batch_qrynum=19 1444    0
create matrix runtime: 0.290000s
Dist spend time：4.85s
Dist finished!
Step4...
Building...
Build spend time：0.01s
Build finished!
Step5...
Tree visualization finished!
Traceback (most recent call last):
  File "/home/xxx/15.SexChrEvolution/04.Evolution/04.Kssdtree/KssdTree.py", line 2, in <module>
    kssdtree.quick(shuf_file='L3K10.shuf', genome_files='01.Z', reference='X.fa.gz', output='Z.newick',  method='nj', mode='r')
  File "/home/xxx/miniconda3/lib/python3.12/site-packages/kssdtree.py", line 423, in quick
    visualize(newick=output, mode=mode)
  File "/home/xxx/miniconda3/lib/python3.12/site-packages/kssdtree.py", line 217, in visualize
    toolutils.view_tree(newick, taxonomy, mode=mode)
  File "/home/xxx/miniconda3/lib/python3.12/site-packages/toolutils.py", line 96, in view_tree
    from ete3 import PhyloTree, TreeStyle, NodeStyle, TextFace
  File "/home/xxx/miniconda3/lib/python3.12/site-packages/ete3/__init__.py", line 51, in <module>
    from .ncbi_taxonomy import *
  File "/home/xxx/miniconda3/lib/python3.12/site-packages/ete3/ncbi_taxonomy/__init__.py", line 40, in <module>
    from .ncbiquery import *
  File "/home/xxx/miniconda3/lib/python3.12/site-packages/ete3/ncbi_taxonomy/ncbiquery.py", line 58, in <module>
    import sqlite3
  File "/home/xxx/miniconda3/lib/python3.12/sqlite3/__init__.py", line 57, in <module>
    from sqlite3.dbapi2 import *
  File "/home/xxx/miniconda3/lib/python3.12/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ImportError: /home/xxx/miniconda3/lib/python3.12/lib-dynload/_sqlite3.cpython-312-x86_64-linux-gnu.so: undefined symbol: sqlite3_deserialize
```

**Comment by yhlink** [comment]
您好，请提供使用的平台和Python版本，推测是ETE3内部可视化问题

**Comment by Flooooooooooooower** [comment]
您好，我使用的Linux，具体的python版本为3.12.2

**Comment by yhlink** [comment]
尝试使用python=3.8.3 ete3=3.1.3
